'use strict';
var app=document.getElementById('app');
var STORAGE='listas-app-v4';
function uid(){return 'i'+Math.random().toString(36).slice(2)+Date.now().toString(36)}
function clone(o){return JSON.parse(JSON.stringify(o))}
var catalog=[
['Aceite de oliva','🫒','Despensa'],['Aceitunas','🫒','Despensa'],['Acelga','🥬','Verduras'],['Aguacate','🥑','Frutas'],['Ajo','🧄','Verduras'],['Albahaca','🌿','Verduras'],['Almendras','🥜','Despensa'],['Arándanos','🫐','Frutas'],['Arroz','🍚','Despensa'],['Atún','🐟','Despensa'],['Avena','🥣','Despensa'],['Azúcar','🧂','Despensa'],['Banana','🍌','Frutas'],['Berenjena','🍆','Verduras'],['Brócoli','🥦','Verduras'],['Café','☕','Bebidas'],['Camarones','🍤','Carnes'],['Cebolla','🧅','Verduras'],['Champiñones','🍄','Verduras'],['Chocolate','🍫','Despensa'],['Espinaca','🥬','Verduras'],['Fresas','🍓','Frutas'],['Huevos','🥚','Lácteos'],['Leche','🥛','Lácteos'],['Limón','🍋','Frutas'],['Manzana','🍎','Frutas'],['Naranja','🍊','Frutas'],['Pan','🍞','Panadería'],['Papas','🥔','Verduras'],['Pollo','🍗','Carnes'],['Queso','🧀','Lácteos'],['Tomate','🍅','Verduras'],['Yogur','🥛','Lácteos'],['Agua','💧','Bebidas'],['Cerveza','🍺','Bebidas'],['Gaseosa','🥤','Bebidas'],['Pasta','🍝','Despensa'],['Sal','🧂','Despensa'],['Harina','🌾','Despensa'],['Detergente','🧴','Limpieza'],['Limpiavidrios','🧴','Limpieza'],['Guantes','🧤','Limpieza'],['Papel higiénico','🧻','Limpieza'],['Jabón','🧼','Higiene'],['Pasta dental','🪥','Higiene'],['Shampoo','🧴','Higiene']
];
var defaultCategories=['Sin categoría','Frutas','Verduras','Despensa','Lácteos','Carnes','Bebidas','Panadería','Limpieza','Higiene'];
function item(name,done,cat){return{id:uid(),name:name,done:!!done,category:cat||'Sin categoría',price:0,qty:1}}
function mkItems(n,done,prefix){var a=[];for(var i=0;i<n;i++)a.push(item(prefix+' '+(i+1),i<done));return a}
function seed(){return{version:4,email:'la86926@gmail.com',settings:{theme:'dark',notifications:false,lastList:false,awake:false,multiply:true,rememberPrice:true,ai:true,showPrices:false,sort:'custom'},categories:defaultCategories.slice(),priceMemory:{},lastListId:'hoy',lists:[
{id:'compras',name:'compras',items:[item('Leche'),item('Pan'),item('Huevos'),item('Arroz'),item('Café')]},
{id:'hoy',name:'Hoy',members:[],items:[item('bolsas, chequeras negras'),item('aspiradora'),item('limpia, vidrios'),item('Guantes para lejía'),item('Bolsa de compras grande para guardar las cosas allí'),item('Llaves'),item('Trapos antipolvo'),item('Jabón'),item('Banco Nación',true),item('Gasolina',true),item('Comprar agua',true),item('Recargar celular',true),item('Ir al banco',true),item('Llevar documentos',true),item('Pagar servicio',true),item('Comprar medicinas',true),item('Llamar a mamá',true)]},
{id:'ch',name:'Chulucanas hoy',items:mkItems(95,94,'Compra Chulucanas')},
{id:'pi',name:'Piura hoy',items:mkItems(77,76,'Compra Piura')},
{id:'lle',name:'Llevar para Piura',items:mkItems(10,1,'Llevar')},
{id:'salud',name:'Vida y salud tienda naturista',items:[item('Avena',true,'Despensa'),item('Semillas de chía',false,'Despensa'),item('Miel',false,'Despensa'),item('Almendras',false,'Despensa')]}
],trash:[{id:uid(),deletedAt:Date.now()-86400000,name:'Sodimac Piura',items:mkItems(81,78,'Artículo')},{id:uid(),deletedAt:Date.now()-7200000,name:'Lista vindela 2/10',items:mkItems(9,8,'Artículo')},{id:uid(),deletedAt:Date.now()-3600000,name:'Precio uno',items:mkItems(21,21,'Artículo')},{id:uid(),deletedAt:Date.now(),name:'al frente',items:mkItems(4,4,'Artículo')},{id:uid(),deletedAt:Date.now(),name:'Verduras',items:mkItems(6,3,'Artículo')}]}}
function normalize(raw){var base=seed(),d=raw&&typeof raw==='object'?raw:base;if(!Array.isArray(d.lists))d.lists=base.lists;if(!Array.isArray(d.trash))d.trash=base.trash;if(!Array.isArray(d.categories))d.categories=base.categories;d.settings=Object.assign({},base.settings,d.settings||{});d.priceMemory=d.priceMemory||{};d.email=d.email||base.email;d.lists.forEach(function(l){l.id=l.id||uid();l.name=l.name||'Sin título';l.members=Array.isArray(l.members)?l.members:[];l.items=Array.isArray(l.items)?l.items:[];l.items.forEach(function(x){x.id=x.id||uid();x.name=x.name||'Artículo';x.done=!!x.done;x.category=x.category||'Sin categoría';x.price=Number(x.price)||0;x.qty=Math.max(1,Number(x.qty)||1)})});d.trash.forEach(function(l){l.id=l.id||uid();l.items=Array.isArray(l.items)?l.items:[]});d.version=4;return d}
var db;try{var saved=localStorage.getItem(STORAGE);if(!saved){saved=localStorage.getItem('listas-app-v2')||localStorage.getItem('listas-app-v3')}db=normalize(JSON.parse(saved||'null'))}catch(e){db=seed()}
var st={tab:'lists',screen:'home',listId:null,product:null,menu:false,modal:null,query:'',listQuery:'',showDone:true,category:'Todos',modalData:null};
function save(){try{localStorage.setItem(STORAGE,JSON.stringify(db))}catch(e){} }
function esc(v){return String(v==null?'':v).replace(/[&<>\"]/g,function(c){return{'&':'&amp;','<':'&lt;','>':'&gt;','\"':'&quot;'}[c]})}
function theme(){var t=db.settings.theme||'dark';if(t==='system'&&window.matchMedia)t=matchMedia('(prefers-color-scheme: light)').matches?'light':'dark';document.body.classList.toggle('light',t==='light');document.querySelector('meta[name=theme-color]').setAttribute('content',t==='light'?'#f4f4f4':'#202020')}
function listById(id){return db.lists.find(function(l){return l.id===id})||null}
function stats(l){var c=0;l.items.forEach(function(x){if(x.done)c++});return{c:c,t:l.items.length,p:l.items.length?Math.round(c/l.items.length*100):0}}
function nav(){return'<nav class="nav"><button data-tab="lists" class="'+(st.tab==='lists'?'on':'')+'"><span class="ni">▤</span>Listas</button><button data-tab="products" class="'+(st.tab==='products'?'on':'')+'"><span class="ni">✿</span>Productos</button><button data-tab="assistant" class="'+(st.tab==='assistant'?'on':'')+'"><span class="ni">✦</span>Asistente</button><button data-tab="profile" class="'+(st.tab==='profile'?'on':'')+'"><span class="ni">♟</span>Perfil</button></nav>'}
function top(title,back,right){return'<div class="top">'+(back?'<button class="icon back" data-action="back" aria-label="Volver">‹</button>':'')+'<h1>'+esc(title)+'</h1>'+(right||'')+'</div>'}
