'use strict';
function modal(){if(!st.modal)return'';var l=listById(st.listId);if(st.modal==='list-menu'&&l)return listMenu(l);if(st.modal==='share'&&l)return shareSheet(l);if(st.modal==='sort')return sortSheet();if(st.modal==='add-item'&&l)return addItemSheet(l);if(st.modal==='edit-item'&&l){var x=l.items.find(function(i){return i.id===st.modalData.id});return x?editItemDialog(l,x):''}if(st.modal==='reorder'&&l){var r=l.items.find(function(i){return i.id===st.modalData.id});return r?reorderSheet(l,r):''}if(st.modal==='select-list')return selectListSheet();if(st.modal==='new-list')return simpleDialog('Nueva lista','Nombre de la lista','','new-list');if(st.modal==='edit-email')return simpleDialog('Editar perfil','Correo electrónico',db.email,'email');if(st.modal==='new-category')return simpleDialog('Nueva categoría','Nombre de la categoría','','category');if(st.modal==='rename-list'){var ll=listById(st.modalData.id);return simpleDialog('Renombrar lista','Nombre',ll?ll.name:'','rename-list')}if(st.modal==='list-actions'){var la=listById(st.modalData.id);return la?listActionsSheet(la):''}if(st.modal==='confirm')return confirmDialog(st.modalData.title,st.modalData.text,st.modalData.action);return''}
function render(){theme();var html='';if(st.tab==='lists'){if(st.screen==='home')html=home();else if(st.screen==='list')html=listView();else if(st.screen==='settings')html=settings();else if(st.screen==='appearance')html=appearance();else if(st.screen==='trash')html=trash();else if(st.screen==='categories')html=categories();else if(st.screen==='expenses')html=expenses();else if(st.screen==='faq')html=faq();else html=home()}else if(st.tab==='products'){html=st.screen==='product-detail'?productDetail():products()}else if(st.tab==='assistant')html=assistant();else html=profile();app.innerHTML=html;afterRender()}
function afterRender(){var ps=document.getElementById('productSearch');if(ps){ps.addEventListener('input',function(){st.query=this.value;render();var p=document.getElementById('productSearch');if(p){p.focus();p.setSelectionRange(p.value.length,p.value.length)}})}var ls=document.getElementById('listSearch');if(ls){ls.addEventListener('input',function(){st.listQuery=this.value;render();var p=document.getElementById('listSearch');if(p){p.focus();p.setSelectionRange(p.value.length,p.value.length)}})}var ai=document.getElementById('addItemInput');if(ai){ai.addEventListener('input',function(){st.modalData=st.modalData||{};st.modalData.q=this.value;render();var p=document.getElementById('addItemInput');if(p){p.focus();p.setSelectionRange(p.value.length,p.value.length)}})}}
function openList(id){if(!listById(id))return;st.tab='lists';st.screen='list';st.listId=id;st.listQuery='';st.modal=null;render()}
function shareText(l){var lines=[l.name];l.items.forEach(function(x){lines.push((x.done?'✓ ':'○ ')+x.name)});return lines.join('\n')}
function copyText(text){if(navigator.clipboard&&navigator.clipboard.writeText){navigator.clipboard.writeText(text).then(function(){toast('Copiado')}).catch(function(){fallbackCopy(text)})}else fallbackCopy(text)}
function fallbackCopy(text){var ta=document.createElement('textarea');ta.value=text;document.body.appendChild(ta);ta.select();try{document.execCommand('copy');toast('Copiado')}catch(e){toast('No se pudo copiar')}document.body.removeChild(ta)}
function doShare(kind){var l=listById(st.listId),text=shareText(l),url='';if(kind==='copy')copyText(text);else if(kind==='native'){if(navigator.share)navigator.share({title:l.name,text:text}).catch(function(){});else copyText(text)}else if(kind==='whatsapp'){url='https://wa.me/?text='+encodeURIComponent(text);window.open(url,'_blank')}else if(kind==='telegram'){url='https://t.me/share/url?url=&text='+encodeURIComponent(text);window.open(url,'_blank')}else if(kind==='email'){location.href='mailto:?subject='+encodeURIComponent(l.name)+'&body='+encodeURIComponent(text)}}
function moveToTrash(l){var idx=db.lists.findIndex(function(x){return x.id===l.id});if(idx<0)return;var copy=clone(l);copy.deletedAt=Date.now();db.trash.unshift(copy);db.lists.splice(idx,1);if(st.listId===l.id)st.listId=null;save();toast('Lista movida a la papelera')}
function addCatalogItem(name,targetList){var p=catalog.find(function(x){return x[0]===name}),x=item(name,false,p?p[2]:'Sin categoría');if(db.settings.rememberPrice&&db.priceMemory[name])x.price=db.priceMemory[name];targetList.items.unshift(x);save();toast('Producto añadido')}
